blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/quebecstudio-mods/.github/blob/main/SECURITY.md
    about: Write to info@quebecstudio.com rather than opening an issue.
